-- Deal progress: the stage a deal the brand said yes to is at (null before that), and when it reached each stage.
ALTER TABLE opportunities ADD COLUMN stage VARCHAR(30);

CREATE TABLE deal_stages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opportunity_id  BIGINT NOT NULL REFERENCES opportunities (id),
    stage           VARCHAR(30) NOT NULL,
    reached_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_deal_stages_opportunity ON deal_stages (opportunity_id);

-- Deals already under way start at the stage their status shows. Earlier stages have no dates.
UPDATE opportunities SET stage = CASE
    WHEN status IN ('CONTRACT_PENDING', 'CONTRACT_TO_SIGN') THEN 'CONTRACT'
    WHEN status IN ('PRODUCT_PENDING', 'PRODUCT_RECEIVED') THEN 'PRODUCT'
    WHEN status = 'CONTENT_TO_CREATE' THEN 'CREATE_CONTENT'
    WHEN status = 'AWAITING_APPROVAL' THEN 'BRAND_APPROVAL'
    WHEN status = 'SCHEDULED_TO_POST' THEN 'POST'
    WHEN status = 'POSTED' AND compensation IN ('GIFTED', 'AFFILIATE') THEN 'DONE'
    WHEN status IN ('POSTED', 'PAYMENT_PENDING') AND EXISTS (SELECT 1 FROM invoices i
        WHERE i.opportunity_id = opportunities.id AND i.status = 'SENT') THEN 'PAYMENT'
    WHEN status IN ('POSTED', 'PAYMENT_PENDING') THEN 'INVOICE'
    WHEN status = 'CLOSED' AND LOWER(closed_reason) = 'paid' THEN 'DONE'
    ELSE NULL END;
