-- Brand contacts: many people per brand, where each one was found, how they've answered, and who never to email.
-- brands.contact_email stays as the brand's best contact, kept in step with the top-ranked row here.

CREATE TABLE brand_contacts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id          BIGINT NOT NULL REFERENCES brands (id),
    email             VARCHAR(320) NOT NULL UNIQUE,   -- cleaned: trimmed, lowercased
    name              VARCHAR(200),
    title             VARCHAR(200),
    role              VARCHAR(20)  NOT NULL,          -- PARTNERSHIPS | PR | MARKETING | FOUNDER | GENERAL | SUPPORT | OTHER
    phone             VARCHAR(50),
    linkedin          VARCHAR(300),
    instagram         VARCHAR(100),
    verified          VARCHAR(10)  NOT NULL DEFAULT 'UNKNOWN',   -- VALID | RISKY | INVALID | UNKNOWN
    verified_at       TIMESTAMP WITH TIME ZONE,
    confidence        INT,                            -- 0-100 from a finder service, null when not given
    emails_sent       INT          NOT NULL DEFAULT 0,
    replies           INT          NOT NULL DEFAULT 0,
    deals_won         INT          NOT NULL DEFAULT 0,
    avg_reply_hours   INT,
    last_contacted_at TIMESTAMP WITH TIME ZONE,
    last_replied_at   TIMESTAMP WITH TIME ZONE,
    bounced           BOOLEAN      NOT NULL DEFAULT FALSE,
    opted_out         BOOLEAN      NOT NULL DEFAULT FALSE,
    score             INT          NOT NULL DEFAULT 0,  -- ranking within the brand and across all contacts
    score_reason      VARCHAR(300),
    notes             VARCHAR(2000),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_brand_contacts_brand ON brand_contacts (brand_id);

-- Every place a contact was seen. Proves where the data came from (asked for under GDPR) and decides what may be
-- shared: contacts bought from finder services are licensed for her own outreach only.
CREATE TABLE contact_sources (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id  BIGINT NOT NULL REFERENCES brand_contacts (id),
    source      VARCHAR(20) NOT NULL,   -- GMAIL | WEBSITE | HUNTER | APOLLO | FINDER | IMPORT | MANUAL | LEAD | GUESS
    source_url  VARCHAR(1000),
    found_at    TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_contact_sources_contact ON contact_sources (contact_id);

-- Web domains a brand owns (glowberry.com, glowberry.co.uk). The main key for matching contacts to brands.
CREATE TABLE brand_domains (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id    BIGINT NOT NULL REFERENCES brands (id),
    domain      VARCHAR(255) NOT NULL UNIQUE,
    crawled_at  TIMESTAMP WITH TIME ZONE        -- last time the website was read for contacts
);
CREATE INDEX ix_brand_domains_brand ON brand_domains (brand_id);

-- Addresses or whole domains never to email again: unsubscribed, bounced, asked to be forgotten. Never pruned.
CREATE TABLE suppression_list (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address   VARCHAR(320) NOT NULL UNIQUE,   -- lowercased email, or a bare domain
    kind      VARCHAR(10)  NOT NULL,          -- EMAIL | DOMAIN
    reason    VARCHAR(30)  NOT NULL,          -- OPTED_OUT | BOUNCED | FORGET_ME | MANUAL
    added_at  TIMESTAMP WITH TIME ZONE NOT NULL
);
