-- Pitch campaigns: saved contact lists, templates with merge fields, and one templated pitch per brand going out
-- through Drafts (she approves each one) and a slow, capped send queue from her own Gmail.

-- A saved filter over the contacts database, e.g. "Partnerships inboxes, never emailed".
CREATE TABLE contact_lists (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    filter_json VARCHAR(4000) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Pitch text with merge fields such as {first_name} and {brand}. Template mode uses no Claude at all.
CREATE TABLE pitch_templates (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(120)  NOT NULL,
    kind           VARCHAR(20)   NOT NULL,     -- COLLAB | UGC | GIFTING | RATES | OTHER
    subject        VARCHAR(300)  NOT NULL,
    body           VARCHAR(8000) NOT NULL,
    follow_up_body VARCHAR(4000),              -- used for every follow-up of a pitch from this template
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE campaigns (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(120) NOT NULL,
    list_id      BIGINT NOT NULL REFERENCES contact_lists (id),
    template_id  BIGINT NOT NULL REFERENCES pitch_templates (id),
    personalise  BOOLEAN NOT NULL DEFAULT FALSE,   -- one opening line per brand from Haiku, in a half-price batch
    status       VARCHAR(10) NOT NULL,             -- ACTIVE | PAUSED | DONE
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

-- One brand in a campaign. attempt 2 is the one retry with the next-ranked person after the first went cold.
CREATE TABLE campaign_targets (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id     BIGINT NOT NULL REFERENCES campaigns (id),
    brand_id        BIGINT NOT NULL REFERENCES brands (id),
    contact_id      BIGINT,
    email           VARCHAR(320) NOT NULL,
    attempt         INT NOT NULL DEFAULT 1,
    -- WAITING_LINE | DRAFTED | APPROVED | SENT | REPLIED | BOUNCED | OPTED_OUT | COLD | MOVED_ON | SKIPPED | STOPPED
    state           VARCHAR(12) NOT NULL,
    opportunity_id  BIGINT,
    draft_id        BIGINT,
    opening_line    VARCHAR(600),
    batch_id        VARCHAR(100),
    approved_at     TIMESTAMP WITH TIME ZONE,
    sent_at         TIMESTAMP WITH TIME ZONE,
    ended_reason    VARCHAR(300),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_campaign_brand_attempt UNIQUE (campaign_id, brand_id, attempt)
);
CREATE INDEX ix_campaign_targets_campaign ON campaign_targets (campaign_id);
CREATE INDEX ix_campaign_targets_brand ON campaign_targets (brand_id);
CREATE INDEX ix_campaign_targets_state ON campaign_targets (state);

-- Bounces, opt-outs and replies seen for campaign emails: drive the auto-pause and the warm-up.
CREATE TABLE campaign_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_id   BIGINT,
    brand_id    BIGINT,
    email       VARCHAR(320),
    kind        VARCHAR(10) NOT NULL,   -- BOUNCE | OPT_OUT | REPLY
    message_id  BIGINT UNIQUE,          -- the email that showed it, so it's counted once
    at          TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_campaign_events_at ON campaign_events (at);

-- A campaign draft: approving it puts it in the slow send queue instead of sending it straight away.
ALTER TABLE drafts ADD COLUMN campaign_target_id BIGINT;
-- When she approved it; set = waiting in the send queue (and not shown in Drafts).
ALTER TABLE drafts ADD COLUMN approved_at TIMESTAMP WITH TIME ZONE;

INSERT INTO pitch_templates (name, kind, subject, body, follow_up_body, created_at, updated_at) VALUES
('Collab pitch', 'COLLAB', 'Collab idea for {brand}',
'Hi {first_name},

{opening_line|I''ve been loving what {brand} has been putting out lately, and I think my audience would too.}

I''m {my_name}, a content creator. {why_you|My followers are always asking me about products like yours, and I only share what I actually use.}

I''d love to put together a collab with {brand}: an honest Reel or TikTok showing how I use it day to day, plus Stories with a link.

My media kit is here: {media_kit}

Would you be open to a quick chat? Happy to send ideas first.

Thanks so much,
{my_name}',
'Hi {first_name},

Just bringing this back to the top of your inbox in case it got buried. I''d still love to create something for {brand}. Happy to share a couple of content ideas if that helps.

Thanks,
{my_name}',
CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('UGC offer', 'UGC', 'UGC videos for {brand}',
'Hi {first_name},

{opening_line|I came across {brand} and immediately pictured the kind of videos I''d make for it.}

I''m {my_name}, and I make UGC: short, natural-looking videos that brands run as ads and on their own pages. No posting on my account needed, and you get the files and usage rights.

{why_you|I think my style would work really well for your products.}

My rates and examples: {rates}

If you''re testing new creative this month, I''d love to send over a few hooks to start.

Best,
{my_name}',
'Hi {first_name},

Following up on my note about UGC videos for {brand}. If new ad creative is on your list, I can turn around a first video quickly.

Best,
{my_name}',
CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gifting ask', 'GIFTING', '{brand} x {my_name}',
'Hi {first_name},

{opening_line|I''ve had my eye on {brand} for a while!}

I''m {my_name}, a content creator, and I''d love to try your products and share my honest thoughts with my audience. There''s no cost to you beyond the product, and if it''s a fit, I''m happy to talk about a paid collab later.

Here''s my media kit: {media_kit}

Would you be open to sending something over?

Thank you,
{my_name}',
'Hi {first_name},

Just checking in on my gifting note. I''d still love to try {brand} and share it with my audience.

Thank you,
{my_name}',
CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Rate card follow-up', 'RATES', 'My rates for {brand}',
'Hi {first_name},

I wanted to share my current rate card in case {brand} is planning creator content soon: {rates}

{why_you|I think my audience is a great match for what you do.}

I''m flexible on packages, and happy to tailor something to your budget.

Best,
{my_name}',
'Hi {first_name},

Following up in case my rate card is useful for {brand}''s plans. Happy to put a package together.

Best,
{my_name}',
CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
