-- The creator's own links (Instagram, TikTok, YouTube, website, portfolio...), shown on the Links page
-- and given to the draft writer so it can include the right URL instead of a placeholder.
CREATE TABLE creator_links (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label      VARCHAR(100)  NOT NULL,
    url        VARCHAR(1000) NOT NULL,
    sort_order INTEGER       NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
