-- What Claude first wrote, kept next to what the creator actually sent, so edits can be learned from.
ALTER TABLE drafts ADD COLUMN original_subject VARCHAR(1000);
ALTER TABLE drafts ADD COLUMN original_body VARCHAR;

-- Messages the creator sent (approved drafts and messages written directly in Gmail/Instagram), with
-- whether the brand replied. The best matches are shown to the draft writer as examples of the creator's voice.
CREATE TABLE writing_examples (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opportunity_id BIGINT,
    draft_id       BIGINT,
    kind           VARCHAR(40)  NOT NULL,   -- REPLY | RATES | FOLLOW_UP | PITCH | DECLINE | ...
    channel        VARCHAR(20)  NOT NULL,   -- EMAIL | INSTAGRAM
    source         VARCHAR(20)  NOT NULL,   -- APP_DRAFT | WRITTEN
    brand_name     VARCHAR(200),
    ai_subject     VARCHAR(1000),
    ai_body        VARCHAR,
    sent_subject   VARCHAR(1000),
    sent_body      VARCHAR      NOT NULL,
    edited         BOOLEAN      NOT NULL,
    got_reply      BOOLEAN      NOT NULL,
    excluded       BOOLEAN      NOT NULL,
    sent_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    replied_at     TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_writing_examples_opportunity ON writing_examples (opportunity_id);
CREATE INDEX idx_writing_examples_sent_at ON writing_examples (sent_at);

-- Start from history: messages the creator already sent to brands become examples straight away.
INSERT INTO writing_examples (opportunity_id, kind, channel, source, brand_name, sent_subject, sent_body,
                              edited, got_reply, excluded, sent_at)
SELECT (SELECT MAX(o.id) FROM opportunities o WHERE o.conversation_id = m.conversation_id),
       CASE m.message_type
           WHEN 'PITCH' THEN 'PITCH'
           WHEN 'CREATOR_FOLLOW_UP' THEN 'FOLLOW_UP'
           WHEN 'SENT_RATES_OR_MEDIA_KIT' THEN 'RATES'
           WHEN 'CREATOR_DECLINED' THEN 'DECLINE'
           ELSE 'REPLY'
       END,
       c.platform, 'WRITTEN', (SELECT b.name FROM brands b WHERE b.id = c.brand_id), m.subject, m.content,
       FALSE,
       EXISTS (SELECT 1 FROM messages r
               WHERE r.conversation_id = m.conversation_id AND r.direction = 'INBOUND'
                 AND r.sent_at > m.sent_at AND r.sent_at <= m.sent_at + INTERVAL '30' DAY),
       FALSE, m.sent_at
FROM messages m
JOIN conversations c ON c.id = m.conversation_id
WHERE m.direction = 'OUTBOUND' AND c.brand_related = TRUE AND LENGTH(m.content) >= 20
  AND m.message_type IN ('PITCH', 'CREATOR_REPLY', 'CREATOR_FOLLOW_UP', 'SENT_RATES_OR_MEDIA_KIT', 'CREATOR_DECLINED');
