-- Brands found by web research that the creator may pitch. Nothing is contacted until the creator
-- turns a lead into a pitch draft and approves it.
CREATE TABLE brand_leads (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(200)  NOT NULL,
    name_key           VARCHAR(200)  NOT NULL,
    website            VARCHAR(1000),
    instagram          VARCHAR(100),
    contact_email      VARCHAR(320),
    contact_source_url VARCHAR(1000),
    fit_reason         VARCHAR(2000),
    pitch_angle        VARCHAR(2000),
    search_query       VARCHAR(500)  NOT NULL,
    status             VARCHAR(20)   NOT NULL,   -- NEW | DRAFTED | DISMISSED
    opportunity_id     BIGINT,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_brand_leads_name_key ON brand_leads (name_key);
