-- Invoices for paid deals. The PDF is rendered on demand from these rows, so nothing binary is stored.
-- Numbers run per year (INV-2026-001, INV-2026-002, ...); seq is the running number within invoice_year.
CREATE TABLE invoices (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number         VARCHAR(40)   NOT NULL UNIQUE,
    invoice_year   INTEGER       NOT NULL,
    seq            INTEGER       NOT NULL,
    opportunity_id BIGINT        NOT NULL REFERENCES opportunities (id),
    brand_id       BIGINT        NOT NULL REFERENCES brands (id),
    bill_to        VARCHAR(1000),
    bill_to_email  VARCHAR(320),
    currency       VARCHAR(10)   NOT NULL,
    amount         NUMERIC(12, 2) NOT NULL,
    line_items     VARCHAR       NOT NULL,   -- JSON: [{"description": "...", "amount": "650.00"}]
    notes          VARCHAR(2000),
    issued_date    DATE          NOT NULL,
    due_date       DATE          NOT NULL,
    sent_at        TIMESTAMP WITH TIME ZONE,
    paid_date      DATE,
    status         VARCHAR(20)   NOT NULL,   -- DRAFT | SENT | PAID | VOID
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_invoice_seq UNIQUE (invoice_year, seq)
);
CREATE INDEX ix_invoices_opportunity ON invoices (opportunity_id);
CREATE INDEX ix_invoices_status ON invoices (status, due_date);

-- An email draft that carries an invoice PDF; sending it marks the invoice sent.
ALTER TABLE drafts ADD COLUMN invoice_id BIGINT;
