-- Accounts that tagged, @mentioned or commented on the creator on Instagram, so brands already engaging with her
-- can become leads. One row per account; is_business is filled in by a Facebook-connection lookup when available
-- (false hides personal accounts such as fans).
CREATE TABLE instagram_engagements (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(100)  NOT NULL UNIQUE,
    mentions        INT           NOT NULL,
    comments        INT           NOT NULL,
    last_kind       VARCHAR(20)   NOT NULL,   -- TAG | MENTION | COMMENT
    last_text       VARCHAR(1000),
    last_permalink  VARCHAR(1000),
    last_seen_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    status          VARCHAR(20)   NOT NULL,   -- NEW | LEAD | DISMISSED
    is_business     BOOLEAN,
    followers       BIGINT,
    checked_at      TIMESTAMP WITH TIME ZONE
);

-- Comment / tag ids already counted, so polling and webhooks never count the same one twice.
CREATE TABLE instagram_seen_events (
    external_id VARCHAR(200) PRIMARY KEY,
    seen_at     TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Where a brand lead came from, and what its Instagram account showed when it was looked up.
ALTER TABLE brand_leads ADD COLUMN source VARCHAR(20) NOT NULL DEFAULT 'WEB';   -- WEB | INSTAGRAM | LOOKUP
ALTER TABLE brand_leads ADD COLUMN ig_followers BIGINT;
ALTER TABLE brand_leads ADD COLUMN ig_bio VARCHAR(1000);
ALTER TABLE brand_leads ADD COLUMN ig_partners VARCHAR(1000);
ALTER TABLE brand_leads ADD COLUMN ig_checked_at TIMESTAMP WITH TIME ZONE;
