-- Contracts brands send: the text read from the PDF (or pasted by the creator), the terms Claude found in it, and
-- the flags the app's own rules raised against her limits. The PDF itself isn't kept; Gmail still has it.
CREATE TABLE contracts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opportunity_id  BIGINT        NOT NULL REFERENCES opportunities(id),
    message_id      BIGINT,
    file_name       VARCHAR(300),
    source          VARCHAR(20)   NOT NULL,   -- PDF | PASTED | LINK
    status          VARCHAR(20)   NOT NULL,   -- CHECKED | LINK_ONLY | UNREADABLE | FAILED
    text_content    VARCHAR,
    terms_json      VARCHAR,
    flags_json      VARCHAR,
    error           VARCHAR(500),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    checked_at      TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_contracts_opportunity ON contracts(opportunity_id);
